ackermann_mux_node:
  ros__parameters:
    topics:
      navigation:
        topic   : drive
        timeout : 0.1
        priority: 10
      joystick:
        topic   : teleop
        timeout : 0.1
        priority: 100
