/**:
  imu_and_wheel_odom_node:
    ros__parameters:
      odom_frame: "odom"
      base_frame: "base_link"
      publish_odom: true
      odom_topic_name: "imu_and_wheel_odom"
      publish_translation: true
      wheel_odom_velocity_scale_x: 1.5
      wheel_odom_expected_rate: 50.0
      mag_north_correction_yaw: 0.0 # Value in rads