mapper:
  updateCondition:
    type: distance
    value: 0.5

  sensorMaxRange: 200

  mapperModule:
    - PointDistanceMapperModule:
        minDistNewPoint: 0.3

input:
  - RandomSamplingDataPointsFilter:
      prob: 0.3

  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.5
      knn: 7
      samplingMethod: 0
      maxBoxDim: inf
      averageExistingDescriptors: 1
      keepNormals: 1
      keepDensities: 0
      keepEigenValues: 0
      keepEigenVectors: 0

icp:
  readingDataPointsFilters:
    - RandomSamplingDataPointsFilter:
        prob: 0.3

  referenceDataPointsFilters:

  outlierFilters:
    - TrimmedDistOutlierFilter:
        ratio: 0.75

  matcher:
    KDTreeMatcher:
      knn: 3
      epsilon: 1
      searchType: 1
      maxDist: 200.0

  errorMinimizer:
    PointToPlaneErrorMinimizer:
      #force4DOF: 1

  inspector: NullInspector

  logger: NullLogger

post:
