mapper:
  updateCondition:
    type: distance
    value: 0.3

  sensorMaxRange: 200

  mapperModule:
    - PointDistanceMapperModule:
        minDistNewPoint: 0.1

input:
  - BoundingBoxDataPointsFilter:
      xMin: -0.5
      xMax: 0.3
      yMin: -0.3
      yMax: 0.3
      zMin: -1
      zMax: 0.5
      removeInside: 1

  - RandomSamplingDataPointsFilter:
      prob: 0.7

  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.5
      knn: 7
      samplingMethod: 0
      maxBoxDim: inf
      averageExistingDescriptors: 1
      keepNormals: 1
      keepDensities: 0
      keepEigenValues: 0
      keepEigenVectors: 0


icp:
  readingDataPointsFilters:
    - RandomSamplingDataPointsFilter:
        prob: 0.4

  referenceDataPointsFilters:

  outlierFilters:
    - TrimmedDistOutlierFilter:
        ratio: 0.75

  matcher:
    KDTreeMatcher:
      knn: 10
      epsilon: 1
      searchType: 1
      maxDist: 200.0

  errorMinimizer:
    PointToPlaneErrorMinimizer:
      force4DOF: 1

  transformationCheckers:
    - CounterTransformationChecker:
        maxIterationCount: 40
    - DifferentialTransformationChecker:
        minDiffRotErr: 0.001
        minDiffTransErr: 0.001
        smoothLength: 3

  inspector: NullInspector

  logger: NullLogger

post: