input:
  - BoundingBoxDataPointsFilter:
      xMin: -0.5
      xMax: 0.3
      yMin: -0.3
      yMax: 0.3
      zMin: -0.3
      zMax: 0.1
      removeInside: 1

  - RandomSamplingDataPointsFilter:
      prob: 0.7

  - AddDescriptorDataPointsFilter:
      descriptorName: probabilityDynamic
      descriptorDimension: 1
      descriptorValues: [0.6] # This value is the initial probability of each point being dynamic


icp:
  outlierFilters:
    - TrimmedDistOutlierFilter:
        ratio: 0.75

  matcher:
    KDTreeMatcher:
      knn: 6
      epsilon: 1
      searchType: 1
      maxDist: 2.0

  errorMinimizer:
    PointToPlaneErrorMinimizer:
      force4DOF: 0

  transformationCheckers:
    - CounterTransformationChecker:
        maxIterationCount: 40
    - DifferentialTransformationChecker:
        minDiffRotErr: 0.001
        minDiffTransErr: 0.001
        smoothLength: 3

  inspector: NullInspector

  logger: NullLogger

post:
  - CutAtDescriptorThresholdDataPointsFilter:
      descName: probabilityDynamic
      useLargerThan: 1
      threshold: 0.8
  - SurfaceNormalDataPointsFilter:
      knn: 10

mapper:
  updateCondition:
    type: delay
    value: 0.3

  sensorMaxRange: 150
 
  mapperModule:
    - DynamicPointsMapperModule:
        thresholdDynamic: 0.75
        alpha: 0.8
        beta: 0.99
        beamHalfAngle: 0.017453292
        epsilonA: 0.01
        epsilonD: 0.01

    - PointDistanceMapperModule:
        minDistNewPoint: 0.05
