joy_node:
  ros__parameters:
    device_id: 0
    # device_name: "Microsoft X-Box One pad"
    # deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval_ms: 0

joy_teleop_node:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      # deadman_buttons: [0]
      axis_mappings:
        drive-speed:
          axis: 2
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 0
          scale: 0.0
          offset: 0.0

    no_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [2, 3, 4, 5, 6, 7, 8, 9, 10]
      axis_mappings:
        drive-speed:
          axis: 2
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 0
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [1]
      axis_mappings:
        drive-speed:
          axis: 2
          scale: 5.0
          offset: 0.0
          deadzone: 0.5
        drive-steering_angle:
          axis: 0
          scale: 0.7853 # 45 deg
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [0]
      message_value:
        data:
          value: 0
