/**:
  # general parameters shared by all vesc-related nodes
  ros__parameters:
    # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
    speed_to_erpm_gain: 3850.0
    speed_to_erpm_offset: 0.0

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: -1.00
    steering_angle_to_servo_offset: 0.5

    port: /dev/sensors/vesc
    duty_cycle_min: 0.0
    duty_cycle_max: 0.0
    current_min: 0.0
    current_max: 100.0
    brake_min: -70000.0
    brake_max: 70000.0
    speed_min: -70000.0
    speed_max: 70000.0
    position_min: 0.0
    position_max: 0.0
    servo_min: 0.3
    servo_max: 0.7

    imu_frame: "imu"

vesc_to_odom_node:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    odom_topic: /odom
    publish_tf: true
    use_servo_cmd_to_calc_angular_velocity: true
    wheelbase: .57
