/**:
  driver:
    ros__parameters:
      frame_id: "imu"
      port: "/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_AU04Q1CD-if00-port0"
      baud: 921600
      adjust_ros_timestamp: true
      reconnect_ms: 500
      AsyncDataOutputType: 0
      AsyncDataOutputFrequency: 1
      syncInMode: 3
      syncInEdge: 0
      syncInSkipFactor: 0
      syncOutMode: 0
      syncOutPolarity: 0
      syncOutSkipFactor: 0
      syncOutPulseWidth_ns: 100000000
      serialCount: 0
      serialStatus: 0
      spiCount: 0
      spiStatus: 0
      serialChecksum: 1
      spiChecksum: 0
      errorMode: 1
      BO1.asyncMode: 1
      BO1.rateDivisor: 4
      BO1.commonField: 0x601
      BO1.timeField: 0x0000
      BO1.imuField: 0x0000
      BO1.attitudeField: 0x0000
      BO1.gps2Field: 0x0000
      BO2.asyncMode: 0
      BO2.rateDivisor: 0
      BO2.commonField: 0x0000
      BO2.timeField: 0x0000
      BO2.imuField: 0x0000
      BO2.gpsField: 0x0000
      BO2.attitudeField: 0x0000
      BO2.insField: 0x0000
      BO2.gps2Field: 0x0000
      BO3.asyncMode: 0
      BO3.rateDivisor: 0
      BO3.commonField: 0x0000
      BO3.timeField: 0x0000
      BO3.imuField: 0x0000
      BO3.gpsField: 0x0000
      BO3.attitudeField: 0x0000
      BO3.insField: 0x0000
      BO3.gps2Field: 0x0000

  decoder:
    ros__parameters:
      use_enu: true
      orientation_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
      angular_velocity_covariance:
        [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
      linear_acceleration_covariance:
        [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
      magnetic_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]

  madgwick_filter:
    ros__parameters:
      gain: 0.01
      use_mag: false
      fixed_frame: "odom"
      publish_tf: false

  bias_observer:
    ros__parameters:
      target_observation_samples: 2000